name: clothes_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_launcher_icons: ^0.13.1
  http: ^0.13.0
  logger: ^1.3.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.1.1
  font_awesome_flutter: ^10.4.0
  image_picker: ^0.8.5+3
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.1
  webview_flutter: ^4.2.2
  flutter_inappwebview: ^5.7.2+3
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.11

flutter_icons:
  android: true
  image_path: 'images/logo/app_logo.png'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/users/users.png
    - images/payment.png
    - images/placeholder.png
